# Generated by Django 2.2 on 2020-05-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='Germany', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='post_code',
            field=models.CharField(default=10000, max_length=255),
            preserve_default=False,
        ),
    ]
