# Generated by Django 2.2 on 2020-05-15 10:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_auto_20200514_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 15, 10, 43, 3, 775710, tzinfo=utc)),
        ),
    ]
