# Generated by Django 2.2 on 2020-05-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0005_auto_20200515_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='Berlin', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default='Germany', max_length=255),
            preserve_default=False,
        ),
    ]
